apiVersion: apps/v1
kind: Deployment
metadata:
   name: comms-router-demo-app
spec:
  selector:
    matchLabels:
      app: comms-router-demo-app
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: comms-router-demo-app
        tier: backend
        track: stable
    spec:
      containers:
        - name: api
          image: 589536902306.dkr.ecr.us-east-2.amazonaws.com/comms-router-ref-app:latest
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true ; do bin/catalina.sh run ; sleep 3 ; done" ]
