apiVersion: v1
kind: Service
metadata:
  name: "service-comms-router-gui"
spec:
  ports:
    - port: 9090
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: "comms-router-gui"
