apiVersion: apps/v1
kind: Deployment
metadata:
   name: comms-router-gui
spec:
  selector:
    matchLabels:
      app: comms-router-gui
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: comms-router-gui
        tier: backend
        track: stable
    spec:
      containers:
        - name: api
          image: 589536902306.dkr.ecr.us-east-2.amazonaws.com/comms-router-gui:latest
          imagePullPolicy: Always
