apiVersion: v1
kind: Service
metadata:
  name: "service-comms-router-api"
spec:
  ports:
    - port: 9090
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: "comms-router-api"
